# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

# { :email => "admin@gmail.com", :password => "adminadmin",  :password_confirmation => 'adminadmin', :nome => "adminadmin", :cognome => "adminadmin", :via => "adminadmin", :ncivico => "1", :cap => 11111, :paese => "adminadmin", :prov => "ro", :datanascita => "1950-12-06", :associazione => nil, :piva_codf => "aaaaaaaaaaaaaaaa", :admin =>true },

 admin = User.create!( :email => "admin@gmail.com", :password => "adminadmin",  :password_confirmation => 'adminadmin', :nome => "adminadmin", :cognome => "adminadmin", :via => "adminadmin", :ncivico => "1", :cap => 11111, :paese => "adminadmin", :prov => "ro", :datanascita => "1950-12-06", :associazione => nil, :piva_codf => "aaaaaaaaaaaaaaaa")
 admin.toggle!(:admin)

User.create!([
	
  { :email => "luca@gmail.com", :password => "lucaluca",  :password_confirmation => 'lucaluca', :nome => "luca", :cognome => "mazzetto", :via => "roma", :ncivico => "1", :cap => 45020, :paese => "rovigo", :prov => "ro", :datanascita => "1950-12-06", :associazione => nil, :piva_codf => "mzzlcu89e12wer43"},
  { :email => "claudio@gmail.com", :password => "claudioclaudio",  :password_confirmation => 'claudioclaudio', :nome => "claudio", :cognome => "foschini", :via => "bari", :ncivico => "10", :cap => 41020, :paese => "ferrara", :prov => "fe", :datanascita => "1920-11-01", :associazione => nil, :piva_codf => "mzzlcu89e12wer43"},
])



Campaign.create!([
  { :nome => "aiuta i cani", :descrizione => "campagna per aiutare i cani \r\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\r\n", :durata => "2014-12-16", :goal => 60000, :chiusa => false, :created_at => "2013-12-27 10:50:11", :updated_at => "2013-12-27 10:50:11", :user_id => 2 },
  
  { :nome => "casa africa", :descrizione => "seconda campagna aiuto per l'africa\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\r\n", :durata => "2014-11-06", :goal => 70000, :chiusa => false, :created_at => "2013-12-27 10:50:51", :updated_at => "2013-12-27 10:50:51", :user_id => 3 },


  { :nome => "salva i senzatetto", :descrizione => "salviamo la gente\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\r\n", :durata => "2015-01-06", :goal => 50000, :chiusa => false, :created_at => "2013-12-27 10:50:51", :updated_at => "2013-12-27 10:50:51", :user_id => 2 }
])

Bill.create!([
  { :totale => 10000, :created_at => "2013-12-27 11:05:25", :updated_at => "2013-12-06 11:05:25", :user_id => 1, :campaign_id => 1 },
  { :totale => 5000, :created_at => "2013-12-27 11:06:31", :updated_at => "2013-12-06 11:06:31", :user_id => 1, :campaign_id => 3 },
  { :totale => 2000, :created_at => "2013-12-27 11:07:30", :updated_at => "2013-12-06 11:07:30", :user_id => 2, :campaign_id => 2 },
  { :totale => 7000, :created_at => "2013-12-27 11:08:31", :updated_at => "2013-12-06 11:08:31", :user_id => 2, :campaign_id => 1 }
])
